# Generated by Django 5.0 on 2023-12-13 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptodata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketdata',
            name='cryptocurrency',
        ),
        migrations.RemoveField(
            model_name='price',
            name='cryptocurrency',
        ),
        migrations.DeleteModel(
            name='Cryptocurrency',
        ),
    ]
