# Generated by Django 5.0 on 2023-12-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptodata', '0002_remove_marketdata_cryptocurrency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketdata',
            name='market_cap_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
