# Generated by Django 4.2.8 on 2023-12-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptodata', '0003_alter_marketdata_market_cap_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdata',
            name='currency',
            field=models.CharField(default='usd', max_length=10),
        ),
        migrations.AddField(
            model_name='price',
            name='currency',
            field=models.CharField(default='usd', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='marketdata',
            unique_together={('date', 'currency')},
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('date', 'currency')},
        ),
    ]
